# Automatically generated by twirp, do not edit manually.
defmodule <%= prefix %>.RPC.<%= service_name %>Client do
  @moduledoc false
  use Twirp.Client, service: <%= prefix %>.RPC.<%= service_name %>Service
end
