# Automatically generated by the twirp compiler, do not edit manually.
defmodule <%= prefix %>.RPC.<%= msg %> do
  @moduledoc false
  defstruct [<%= for k <- keys, do: ":#{k}," %>]

  def new(vals) do
    struct(__MODULE__, vals)
  end

  def encode(%__MODULE__{}=map) do
    map =
      map
      |> Map.from_struct
      |> Enum.reject(fn {_, val} -> val == nil end)
      |> Enum.into(%{})

    :<%= pb_mod %>.encode_msg(map, :<%= msg %>)
  end

  def decode(bin) do
    map = :<%= pb_mod %>.decode_msg(bin, :<%= msg %>)
    struct(__MODULE__, map)
  end
end
