# Automatically generated by twirp, do not edit manually.
defmodule <%= prefix %>.RPC.<%= service_name %>Service do
  @moduledoc false
  use Twirp.Service

  package "<%= package %>"
  service "<%= service_name %>"

  <%= Enum.map methods, fn(method) -> %>
    rpc <%= method %>
  <% end %>
end

